### ISSUE TITLE
解决 'jumping scrollbar' 问题的几种方式

### ISSUE THREAD

**Issue by jankjn** [jankjn/blog#3]
## Jumping Scrollbar
在页面中水平居中一个元素我们往往会使用 ` margin: 0 auto;` 的方式。如果页面存在高度变化(eg. 点击加载更多, 模态框 etc)导致滚动条显隐, 居中元素的横向位置就会变化, 影响用户体验。
[点击查看示例](http://codepen.io/z-a-c-h/pen/WRvmMJ)
### 最简单的办法
```css
html {
    overflow-y: scroll;
}
```
保持滚动条始终显示, 缺点是浪费空间，多余元素影响观感。
### margin-left
元素位置抖动的原因是页面右侧出现滚动条占用了宽度，只要在左侧也撑起相同宽度，即可保持居中位置。
```css
/* 或者 padding-left */
.wrapper {
    margin-left: calc(100vw - 100%);
}
```
### fixed width
与两边减去相同宽度的方式不同，保持居中容器的宽度和相对位置不变也是一种做法。
```css
html {
    width:100vw;
    overflow-x:hidden;
}
```
缺点是影响整个页面, 右侧可能会有元素被滚动条遮住

ps: 还有张鑫旭菊苣在博客中提到的 "终极解决方案"，也属于最后一种固定宽度的方式，不过应该是涉及了兼容性处理 fallback 的一些东西，有的地方不是很理解，先记录在这里。
```css
html {
  overflow-y: scroll;
}

/*
:root 根元素选择器在 html 中即指 `<html>` 元素 (css 标准不止适用于 html),
且作为伪类选择器，优先级高于 html tag 选择器
*/
:root {
  overflow-y: auto;
  overflow-x: hidden;
}

:root body {
  position: absolute;
}

body {
  width: 100vw;
  overflow: hidden;
}
```

参考资料:
- [Fix 'jumping scrollbar' issue using only CSS](https://aykevl.nl/2014/09/fix-jumping-scrollbar)
- [小tip:CSS vw让overflow:auto页面滚动条出现时不跳动](http://www.zhangxinxu.com/wordpress/2015/01/css-page-scrollbar-toggle-center-no-jumping/)
